// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZ0PRLgYj8GioYGYOV3eec4zWFpeHsY8',
    appId: '1:330570815237:web:6b7455722d7219ddb6c96c',
    messagingSenderId: '330570815237',
    projectId: 'kaagnews',
    authDomain: 'kaagnews.firebaseapp.com',
    storageBucket: 'kaagnews.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQg4SmcE8kaZzeJ6M6AOUtIFgG6ZVkFM',
    appId: '1:330570815237:android:d638c91d3fe40aa0b6c96c',
    messagingSenderId: '330570815237',
    projectId: 'kaagnews',
    storageBucket: 'kaagnews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23z5oZLh9anbEtG7u-RJqtdQUEjPCars',
    appId: '1:330570815237:ios:59a89299c0ba8188b6c96c',
    messagingSenderId: '330570815237',
    projectId: 'kaagnews',
    storageBucket: 'kaagnews.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23z5oZLh9anbEtG7u-RJqtdQUEjPCars',
    appId: '1:330570815237:ios:59a89299c0ba8188b6c96c',
    messagingSenderId: '330570815237',
    projectId: 'kaagnews',
    storageBucket: 'kaagnews.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHZ0PRLgYj8GioYGYOV3eec4zWFpeHsY8',
    appId: '1:330570815237:web:9ec498cce469d4a9b6c96c',
    messagingSenderId: '330570815237',
    projectId: 'kaagnews',
    authDomain: 'kaagnews.firebaseapp.com',
    storageBucket: 'kaagnews.firebasestorage.app',
  );
}
